trigger: none

schedules:
- cron: "0 3 * * *"
  displayName: Daily update from upstream
  branches:
    include:
    - main
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  displayName: 'Checkout repository'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: mikkokok
    KeyVaultName: kv-kokkonenpro
    SecretsFilter: 'upstreamRepoUrl'
  name: FetchSecrets
  displayName: 'Fetch upstream repo URL from Key Vault'

- script: |
    git remote add upstream $(upstreamRepoUrl)
    git fetch upstream

    for branch in $(git branch -r | grep 'upstream/' | grep -v 'HEAD' | sed 's/upstream\///'); do
      echo "Updating branch: $branch"
      git checkout $branch -- || git checkout -b $branch origin/$branch --
      git merge upstream/$branch --allow-unrelated-histories --no-edit
      git push origin $branch
    done
  displayName: 'Merge all upstream branches and push'